# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: Install Yarn
        run: npm install -g yarn
      - name: Install Dependencies Api
        run: |
          cd api
          yarn install
      - name: Install Dependencies and build in Client
        run: |
          cd client
          yarn install
          yarn build
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-client
          path: client/build
      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: xephang.online
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASS }}
          source: "client/build"
          target: "/home/dev/thienphu/test"
      # - name: Test
      #   run: npm test
      # - name: Lint
      #   run: npm run lint
